version: '3.8'
services:
  web:
    container_name: httpd
    build: 
        context: ./php
        dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    links:
      - db
    ports:
      - 8000:80
      
  # db:
  #   container_name: mysql-db
  #   image: mysql
  #   volumes:
  #     - ./db:/var/lib/mysql
  #   ports:
  #     - 3306:3306
  #   restart: always
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: thehours
  # phpmyadmin:
  #   container_name: phpmyadmin
  #   image: phpmyadmin
  #   ports: 
  #     - 8080:80
  #   restart: always
  #   environment:
  #     PMA_HOST: db
  #     PMA_USER: root
  #     PMA_PASSWORD: root
  #   depends_on:
  #     - db
  #   links:
  #     - db:db
    